name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  build:
    # -------- https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    name: Build distribution 📦
    runs-on: ubuntu-20.04

    steps:
      # -------- https://github.com/actions/checkout
      # check out your repository files onto the runner, so that the workflow can access them
      - uses: actions/checkout@v4
        with:
          lfs: false
        
      # - name: Checkout LFS objects
      #   run: git lfs checkout

      # -------- https://github.com/actions/setup-python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.6"

      # --------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pytest pytest-cov
          pip install -r requirements.txt

      # --------
      - name: Format with black
        run: |
          black . --line-length=128
        
      - name: Commit changes in formatting
        uses: EndBug/add-and-commit@v9
        with:
          add: '*.py'
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Formatted code with black."
          default_author: github_actor
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # -------- checks
      # - name: Print working directory for debugging in CI
      #   run: pwd

      # - name: List directory contents
      #   run: ls -la tests/
        
      # --------
      - name: Update README table
        run: |
          python src/utils/update_readme.py

      - name: Commit updated README.MD
        uses: EndBug/add-and-commit@v9
        with:
          add: 'README.MD'
          author_name: GitHub Actions
          author_email: actions@github.com
          message: 'Updated README.MD with new table data.'
          default_author: github_actor
          github_token: ${{ secrets.GITHUB_TOKEN }}